[loggers]
keys=root,sublog

[logger_root]
level=DEBUG
handlers=consoleHandler

[logger_sublog]
level=DEBUG
handlers=consoleHandler,fileHandler
qualname=sublog
propagate=0

[handlers]
keys=consoleHandler,fileHandler

[handler_consoleHandler]
class=StreamHandler
args=(sys.stdout,)
level=INFO
formatter=myFormatter

[handler_fileHandler]
class=FileHandler
args=('imdup.log', 'w')
level=DEBUG
formatter=myFormatter

[formatters]
keys=simpleFormatter,myFormatter

[formatter_simpleFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s

[formatter_myFormatter]
format=%(asctime)s,%(msecs)d %(levelname)s [%(name)s:%(threadName)s] %(message)s (%(funcName)s)
datefmt=%H:%M:%S