# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crecord.proto\x12\x04\x64\x65mo\"\xc1\x01\n\tRunRecord\x12\x16\n\x0eschema_version\x18\x01 \x01(\r\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08platform\x18\x04 \x01(\t\x12\x11\n\tdate_time\x18\x05 \x01(\x02\x12\x10\n\x08\x64ur_secs\x18\x06 \x01(\x02\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x10\n\x08num_dirs\x18\x08 \x01(\r\x12\x11\n\tnum_files\x18\t \x01(\r\x12\r\n\x05\x65rror\x18\x0b \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'record_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RUNRECORD']._serialized_start=23
  _globals['_RUNRECORD']._serialized_end=216
# @@protoc_insertion_point(module_scope)
