# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crecord.proto\x12\x04\x64\x65mo\"\xd4\x02\n\tRunRecord\x12\x16\n\x0eschema_version\x18\x01 \x01(\r\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0c\n\x04uuid\x18\x03 \x01(\x0c\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x10\n\x08platform\x18\x06 \x01(\t\x12\x12\n\nstart_time\x18\x07 \x01(\x02\x12\x10\n\x08\x64ur_secs\x18\x08 \x01(\x02\x12\x0e\n\x06status\x18\t \x01(\t\x12\x0f\n\x07root_id\x18\n \x01(\x0c\x12\x10\n\x08num_dirs\x18\x0b \x01(\r\x12\x11\n\tnum_files\x18\x0c \x01(\r\x12)\n\x05\x65xtra\x18\r \x03(\x0b\x32\x1a.demo.RunRecord.ExtraEntry\x12\r\n\x05\x65rror\x18\x0e \x01(\t\x12\x0c\n\x04tags\x18\x0f \x03(\t\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xbb\x01\n\tDirRecord\x12\x16\n\x0eschema_version\x18\x01 \x01(\r\x12\n\n\x02id\x18\x02 \x01(\x0c\x12\x11\n\tparent_id\x18\x03 \x01(\x0c\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x11\n\tdate_time\x18\x05 \x01(\x02\x12\x12\n\nfiles_hash\x18\x06 \x01(\t\x12\x11\n\tdirs_hash\x18\x07 \x01(\t\x12\x10\n\x08\x66ile_ids\x18\x08 \x03(\x0c\x12\x0f\n\x07\x64ir_ids\x18\t \x03(\x0c\x12\x0c\n\x04tags\x18\n \x03(\t\"}\n\nFileRecord\x12\x16\n\x0eschema_version\x18\x01 \x01(\r\x12\n\n\x02id\x18\x02 \x01(\x0c\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\tdate_time\x18\x04 \x01(\x02\x12\x0e\n\x06length\x18\x05 \x01(\x04\x12\x0c\n\x04hash\x18\x06 \x01(\t\x12\x0c\n\x04tags\x18\n \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'record_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RUNRECORD_EXTRAENTRY._options = None
  _RUNRECORD_EXTRAENTRY._serialized_options = b'8\001'
  _globals['_RUNRECORD']._serialized_start=23
  _globals['_RUNRECORD']._serialized_end=363
  _globals['_RUNRECORD_EXTRAENTRY']._serialized_start=319
  _globals['_RUNRECORD_EXTRAENTRY']._serialized_end=363
  _globals['_DIRRECORD']._serialized_start=366
  _globals['_DIRRECORD']._serialized_end=553
  _globals['_FILERECORD']._serialized_start=555
  _globals['_FILERECORD']._serialized_end=680
# @@protoc_insertion_point(module_scope)
